<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-592MAVU8" failures="0" tests="13" name="com.test.Dataprovider1" time="0.043" errors="1" timestamp="2022-12-16T17:29:05 IST" skipped="0">
  <testcase classname="com.test.Dataprovider1" name="Info" time="0.002"/>
  <system-out/>
  <testcase classname="com.test.Dataprovider1" name="verifyLogin" time="0.002"/>
  <system-out/>
  <testcase classname="com.test.Dataprovider1" name="verifyINT" time="0.001"/>
  <system-out/>
  <testcase classname="com.test.Dataprovider1" name="verifyLogin" time="0.001"/>
  <system-out/>
  <testcase classname="com.test.Dataprovider1" name="Info" time="0.002"/>
  <system-out/>
  <testcase classname="com.test.Dataprovider1" name="verifyINT" time="0.002"/>
  <system-out/>
  <testcase classname="com.test.Dataprovider1" name="Info" time="0.001"/>
  <system-out/>
  <testcase classname="com.test.Dataprovider1" name="verifyLogin" time="0.001"/>
  <system-out/>
  <testcase classname="com.test.Dataprovider1" name="loginData" time="0.004">
    <error message="
[public void com.test.Dataprovider1.loginData(java.lang.Object)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: loginData([java.lang.Object arg0])
Arguments: [(java.lang.String) Admin,(java.lang.String) admin123]" type="org.testng.internal.reflect.MethodMatcherException">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void com.test.Dataprovider1.loginData(java.lang.Object)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: loginData([java.lang.Object arg0])
Arguments: [(java.lang.String) Admin,(java.lang.String) admin123]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:46)
at org.testng.internal.Parameters.injectParameters(Parameters.java:918)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:37)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- loginData -->
  <system-out/>
  <testcase classname="com.test.Dataprovider1" name="verifyINT" time="0.002"/>
  <system-out/>
  <testcase classname="com.test.Dataprovider1" name="Info" time="0.003"/>
  <system-out/>
  <testcase classname="com.test.Dataprovider1" name="Info" time="0.003"/>
  <system-out/>
  <testcase classname="com.test.Dataprovider1" name="Info" time="0.019"/>
  <system-out/>
</testsuite> <!-- com.test.Dataprovider1 -->
